"""updated keywords table

Revision ID: 0e48b06a92a5
Revises: 32e8ad225171
Create Date: 2024-10-12 22:04:46.456613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e48b06a92a5'
down_revision: Union[str, None] = '32e8ad225171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('created_at', sa.DateTime(), server_default=sa.func.current_timestamp(), nullable=False))
    op.add_column('keywords', sa.Column('created_by_user_id', sa.BigInteger(), server_default=sa.text('(243332147379830785)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keywords', 'created_by_user_id')
    op.drop_column('keywords', 'created_at')
    # ### end Alembic commands ###
