"""added emojis table

Revision ID: b3e3e611f0d4
Revises: 74b8d382a9c1
Create Date: 2024-10-13 02:18:52.393093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e3e611f0d4'
down_revision: Union[str, None] = '74b8d382a9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emojis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emoji_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), server_default=sa.text('(243332147379830785)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emojis_emoji_name'), 'emojis', ['emoji_name'], unique=True)
    op.create_table('emojis_keywords_association',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('emoji_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emoji_id'], ['emojis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('keyword_id', 'emoji_id')
    )
    op.drop_index('ix_new_links_url', table_name='links')
    op.create_index(op.f('ix_links_url'), 'links', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_url'), table_name='links')
    op.create_index('ix_new_links_url', 'links', ['url'], unique=1)
    op.drop_table('emojis_keywords_association')
    op.drop_index(op.f('ix_emojis_emoji_name'), table_name='emojis')
    op.drop_table('emojis')
    # ### end Alembic commands ###
